image:
  file: .gitpod.Dockerfile
  context: .gitpod

ports:
  - port: 8001

tasks:
  - init: |
      composer install;
      sh ./.gitpod/phpMyAdmin.sh;
      gp preview $(gp url 8001);
  - name: Apache
    command: >
      apachectl start &&
      multitail /var/log/apache2/access.log -I /var/log/apache2/error.log
vscode:
  extensions:
    - humao.rest-client@0.24.2:tiNIwP71m33jcKqZcyO2EQ==
    - rokoroku.vscode-theme-darcula@1.2.1:N6IL8ttOWcXvr67zJpASvQ==