image:
  file: .gitpod.Dockerfile
  context: .gitpod

ports:
  - port: 8001

tasks:
  - name: Apache
    command: >
      apachectl start &&
      multitail /var/log/apache2/access.log -I /var/log/apache2/error.log
  - init: |
      composer install;
      yarn;
      sh ./.gitpod/phpMyAdmin.sh;
      yarn build;
      gp preview $(gp url 8001);
